development:
test:
production:
  access_key_id: <%= ENV['S3_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['S3_SECRET_KEY'] %>
  bucket: <%= ENV['S3_BUCKET_NAME'] %>



#And add this ENV VARIABLE in your heroku app

#heroku config:add S3_ACCESS_KEY='your_key'
#heroku config:add S3_SECRET_KEY='your_secret'
#heroku config:add S3_BUCKET_NAME='your_nucket_name'
